kind: Pod
apiVersion: v1
metadata:
  generateName: nginx-79b8677687-
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "cilium",
          "interface": "eth0",
          "ips": [
              "10.0.11.90"
          ],
          "mac": "f2:6e:14:ac:3a:7d",
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "cilium",
          "interface": "eth0",
          "ips": [
              "10.0.11.90"
          ],
          "mac": "f2:6e:14:ac:3a:7d",
          "default": true,
          "dns": {}
      }]
    kubernetes.io/limit-ranger: >-
      LimitRanger plugin set: cpu, ephemeral-storage, memory request for
      container nginx; cpu, memory limit for container nginx
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  resourceVersion: '1034900416'
  name: nginx-79b8677687-frkt4
  uid: e85db8b8-7063-4f70-a8bd-30e455b463b4
  creationTimestamp: '2023-06-16T08:46:11Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-06-16T08:46:11Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:deployment': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"ea02c388-0ca7-432c-93dd-34855cd24ce9"}': {}
        'f:spec':
          'f:containers':
            'k:{"name":"nginx"}':
              .: {}
              'f:image': {}
              'f:imagePullPolicy': {}
              'f:name': {}
              'f:ports':
                .: {}
                'k:{"containerPort":8080,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:protocol': {}
              'f:resources': {}
              'f:terminationMessagePath': {}
              'f:terminationMessagePolicy': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
    - manager: multus
      operation: Update
      apiVersion: v1
      time: '2023-06-16T08:46:11Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
            'f:k8s.v1.cni.cncf.io/networks-status': {}
      subresource: status
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2023-06-16T08:46:18Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.0.11.90"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
      subresource: status
  namespace: zlic-nlendi1
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: nginx-79b8677687
      uid: ea02c388-0ca7-432c-93dd-34855cd24ce9
      controller: true
      blockOwnerDeletion: true
  labels:
    app: nginx
    deployment: nginx
    pod-template-hash: 79b8677687
spec:
  nodeSelector:
    node-role.kubernetes.io/app: ''
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-7zdb8
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: worker-0f6e
  securityContext:
    seLinuxOptions:
      level: 's0:c41,c5'
    fsGroup: 1001650000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - resources:
        limits:
          cpu: 600m
          memory: 768Mi
        requests:
          cpu: 10m
          ephemeral-storage: 100Ki
          memory: 100Mi
      terminationMessagePath: /dev/termination-log
      name: nginx
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1001650000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      ports:
        - containerPort: 8080
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: kube-api-access-vc62r
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: >-
        image-registry.openshift-image-registry.svc:5000/zlic-nlendi1/nginx@sha256:3130ef5f1ba59d7c70e917cb60ced2838ddd64e42ea174bb55cbb20d8a2abaa8
  serviceAccount: default
  volumes:
    - name: kube-api-access-vc62r
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/memory-pressure
      operator: Exists
      effect: NoSchedule
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-06-16T08:46:11Z'
    - type: Ready
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-06-16T08:46:18Z'
    - type: ContainersReady
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-06-16T08:46:18Z'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-06-16T08:46:11Z'
  hostIP: 194.182.161.247
  podIP: 10.0.11.90
  podIPs:
    - ip: 10.0.11.90
  startTime: '2023-06-16T08:46:11Z'
  containerStatuses:
    - restartCount: 0
      started: true
      ready: true
      name: nginx
      state:
        running:
          startedAt: '2023-06-16T08:46:17Z'
      imageID: >-
        image-registry.openshift-image-registry.svc:5000/zlic-nlendi1/nginx@sha256:3130ef5f1ba59d7c70e917cb60ced2838ddd64e42ea174bb55cbb20d8a2abaa8
      image: >-
        image-registry.openshift-image-registry.svc:5000/zlic-nlendi1/nginx@sha256:3130ef5f1ba59d7c70e917cb60ced2838ddd64e42ea174bb55cbb20d8a2abaa8
      lastState: {}
      containerID: 'cri-o://3e5678bb0ae62c7ef12aca73dfe7300fae3f1dc745316dacc57058126ede3f74'
  qosClass: Burstable
