apiVersion: apps/v1
kind: Deployment
metadata:
  name: derlendi
name: derlendi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: derlendi
  template:
    metadata:
      labels:
        app: derlendi
    spec:
      containers:
      - name: derlendi
        image: ghcr.io/derlendi/m109/6.2:v1
        ports:
        - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: derlendi
spec:
  selector:
    app: derlendi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: derlendi
spec:
  to:
    kind: Service
    name: derlendi
  port:
    targetPort: 8080
  tls:
    termination: edge